name: Simple CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "hello"
      - name: Say hello again
        run: echo "hello again"
